/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package managementsys;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MOON
 */
public class StaffPannel extends javax.swing.JFrame {

    /**
     * Creates new form StudentPannel
     */
    private ArrayList staffObjects = new ArrayList(); //ArrayList to save Staff objects in an array (Dynamic Array)
    
    public StaffPannel() {
        initComponents();
        try{
            FileInputStream fi = new FileInputStream(new File("Staff Data.txt")); //Read File Staff data.txt
            ObjectInputStream oi = new ObjectInputStream(fi); //setup object stream
            staffObjects.addAll((ArrayList)oi.readObject()); //read object from file then save in student objects
            oi.close(); //close object stream
            fi.close(); //close file
        }catch (Exception ex){ }
        createTable();
    }
    //Method to create table
    void createTable(){  //Go to event file to understand what is going on here.....
        String data[][] = new String[staffObjects.size()][5];
        String column[]={"ERN NO","NAME","FATHER NAME","PH NO","ADDRESS"};
        for(int i = 0; i<staffObjects.size();i++){
            data[i][0] = String.valueOf(((Staff)staffObjects.get(i)).getErnNo());
            data[i][1] = ((Staff)staffObjects.get(i)).getName();
            data[i][2] = ((Staff)staffObjects.get(i)).getFName();
            data[i][3] = ((Staff)staffObjects.get(i)).getAddress();
            data[i][4] = ((Staff)staffObjects.get(i)).getPhNo();
        }
        DefaultTableModel tableModel = new DefaultTableModel(3,3);
        tableModel.setDataVector(data,column);
        table.setModel(tableModel);
    }
    // Method to save Staff Array in file Staff Data.txt
    private void saveStaffObjects(){
        try{
            FileOutputStream f = new FileOutputStream(new File("Staff Data.txt")); //Create File
            ObjectOutputStream o = new ObjectOutputStream(f); //Setup Object output stream
            o.writeObject(staffObjects); //Write Object to file
            o.close(); //close object stream
            f.close(); //close file
        }catch(IOException e){}
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        totalStaffButton = new javax.swing.JButton();
        searchErnNoButton = new javax.swing.JButton();
        removeErnNoButton = new javax.swing.JButton();
        removeErnNo = new javax.swing.JTextField();
        searchErnNo = new javax.swing.JTextField();
        addNew = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENT PANNEL");
        setLocation(new java.awt.Point(200, 50));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 810, 620));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setEnabled(false);
        table.setFillsViewportHeight(true);
        table.setRowHeight(20);
        staffTable.setViewportView(table);

        getContentPane().add(staffTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 690, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("STAFF PANNEL");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 310, 60));

        back.setBackground(new java.awt.Color(255, 0, 0));
        back.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 480, 180, 30));

        totalStaffButton.setBackground(new java.awt.Color(0, 240, 240));
        totalStaffButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalStaffButton.setText("TOTAL STAFF");
        totalStaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalStaffButtonActionPerformed(evt);
            }
        });
        getContentPane().add(totalStaffButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, 180, 30));

        searchErnNoButton.setBackground(new java.awt.Color(0, 240, 240));
        searchErnNoButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchErnNoButton.setText("SEARCH BY ErnNo");
        searchErnNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchErnNoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchErnNoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 150, 30));

        removeErnNoButton.setBackground(new java.awt.Color(0, 240, 240));
        removeErnNoButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        removeErnNoButton.setText("REMOVE BY ErnNo");
        removeErnNoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeErnNoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeErnNoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 150, 30));
        getContentPane().add(removeErnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 170, 30));
        getContentPane().add(searchErnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 170, 30));

        addNew.setBackground(new java.awt.Color(0, 240, 240));
        addNew.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        addNew.setText("ADD NEW");
        addNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewActionPerformed(evt);
            }
        });
        getContentPane().add(addNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 380, 180, 30));

        jLabel4.setText("THE SUMMAYA'S GROUP OF COLLEGE SYSTEM KARACHI");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 550, 410, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/managr1.jpg"))); // NOI18N
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 589));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
     MainMenus obj= new MainMenus(); //Creating main menu
             obj.setVisible(true); //main menu appearing
             dispose(); //current frame closing
    }//GEN-LAST:event_backActionPerformed

    private void totalStaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalStaffButtonActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(jPanel1,staffObjects.size()); // showing size of student array
    }//GEN-LAST:event_totalStaffButtonActionPerformed

    private void searchErnNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchErnNoButtonActionPerformed
        // TODO add your handling code here:
        int ernNo = Integer.parseInt(searchErnNo.getText()); //get ern no from user input
        int i; 
        for(i=0;i<staffObjects.size();i++){ //loop check every entry in staff array
            if(((Staff)staffObjects.get(i)).checkErnNo(ernNo)){ //check if ern is same if yes break loop
                break;
            }
        }
        Staff temp = ((Staff)staffObjects.get(i)); //save required staff in temp 
        JOptionPane.showMessageDialog(jPanel1,"Ern No: "+temp.getErnNo()+"\nName: "+temp.getName()+"\nFather Name: "+temp.getFName()+"\nPhone No: "+temp.getPhNo()+"\nAddress: "+temp.getAddress()); // display infor
        searchErnNo.setText(""); //clear field
    }//GEN-LAST:event_searchErnNoButtonActionPerformed

    private void removeErnNoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeErnNoButtonActionPerformed
        // TODO add your handling code here:
        int ernNo = Integer.parseInt(removeErnNo.getText()); //get ern from user
        int i; 
        for(i=0;i<staffObjects.size();i++){ //loop to check every entry
            if(((Staff)staffObjects.get(i)).checkErnNo(ernNo)){ //break loop if ern is same
                break;
            }
        }
        staffObjects.remove(i); //remove entry stored at i index in staff array
        createTable(); //create table
        removeErnNo.setText(""); //clear field
        saveStaffObjects(); //save staff array in file
    }//GEN-LAST:event_removeErnNoButtonActionPerformed

    private void addNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewActionPerformed
      AddNew1 obj= new AddNew1(); 
             obj.setVisible(true);
             dispose();
    }//GEN-LAST:event_addNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffPannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffPannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNew;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField removeErnNo;
    private javax.swing.JButton removeErnNoButton;
    private javax.swing.JTextField searchErnNo;
    private javax.swing.JButton searchErnNoButton;
    private javax.swing.JScrollPane staffTable;
    private javax.swing.JTable table;
    private javax.swing.JButton totalStaffButton;
    // End of variables declaration//GEN-END:variables
}
